---
title: "flat_first.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```
## Get a message with a number of rows
You can get a message with the number of rows in a data frame of interest with `get_df_nrows()`.

```{r development}
library(glue) # Au tout début
data <- iris
message("The dataset is composed of 150 observations")
nrow_df <- nrow(data)
message(glue("The dataset is composed of {nrow_df} observations"))
```
```{r development, include=FALSE}
library(testthat)

get_df_nrows <- function(data) 
{nrow(data)
+ message(glue("The dataset is composed of {nrow_df} observations"))}
```
# get_df_rows
    
```{r function-get_df_rows}
#'Get a message with number of rows of the dataset you will be working with
#'
#' @param df data.frame. The dataset to be used
#' @importFrom glue glue
#' @return Used for side effect. Outputs a message in the console
#' @export
#' @examples
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observations"))
  return(nrow_df)
}
```
  
```{r example-get_df_rows}
get_df_nrows(df = iris)
```
  

```{r tests-get_df_nrows}
test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(df = mtcars),
    regexp = "The dataset is composed of 32 observations"
  )
})

```
```
  
<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->




```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_get_info.Rmd", vignette_name = "Get info about the dataset")
```


