# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

#'Get a message with number of rows of the dataset you will be working with
#'
#' @param df data.frame. The dataset to be used
#' @importFrom glue glue
#' @return Used for side effect. Outputs a message in the console
#' @export
#' @examples
#' get_df_nrows(df = iris)
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observations"))
  return(nrow_df)
}
